name: Push to GCS

on:
  push:
    branches:
      - master

jobs:
  upload_to_gcs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/137452212901/locations/global/workloadIdentityPools/ladsite-wli-pool/providers/ladsite-github"
          service_account: "ladsite-jump-iac@sycomp-storage.iam.gserviceaccount.com"        

      - name: Publish file
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'test'
          destination: 'ladsite/jump_iac/latest'
          process_gcloudignore: false
          parent: true

#